engines:
  sonar-java:
    enabled: true
    config:
      sonar.java.source: 8
      test_patterns:
        - src/test/**
  pmd:
    enabled: true
    config:
      rules:
        - "java-basics"
        - "java-design"
