language: java
jdk: oraclejdk8
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - mvn test -B
  - mv $TRAVIS_BUILD_DIR/target/site/jacoco-ut/jacoco.xml $TRAVIS_BUILD_DIR/
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT --prefix $TRAVIS_BUILD_DIR/src/main/java
