package com.epam.page.object.generator.integration.data;

/**
 * Pair of classes: manual and test (generated by POG)
 * that are comparing to each other
 */
public class TestClassesData {
    private String manualClassFullName;
    private String manualClassFilePath;
    private String jsonPath;
    private String testURL;
    private boolean checkLocatorUniqueness;
    private boolean forceGenerateFiles;
    private Class manualClass;

    private String testClassFullName;
    private String testClassFilePath;
    private Class testClass;

    public TestClassesData(String manualClassFullName, String manualClassFilePath,
                           String jsonPath, String testURL, boolean checkLocatorUniqueness,
                           boolean forceGenerateFiles, String testClassFullName,
                           String testClassFilePath) {
        this.manualClassFullName = manualClassFullName;
        this.manualClassFilePath = manualClassFilePath;
        this.jsonPath = jsonPath;
        this.testURL = testURL;
        this.checkLocatorUniqueness = checkLocatorUniqueness;
        this.forceGenerateFiles = forceGenerateFiles;
        this.testClassFullName = testClassFullName;
        this.testClassFilePath = testClassFilePath;
    }

    public String getManualClassFullName() {
        return manualClassFullName;
    }

    public void setManualClassFullName(String manualClassFullName) {
        this.manualClassFullName = manualClassFullName;
    }

    public String getManualClassFilePath() {
        return manualClassFilePath;
    }

    public void setManualClassFilePath(String manualClassFilePath) {
        this.manualClassFilePath = manualClassFilePath;
    }

    public String getJsonPath() {
        return jsonPath;
    }

    public void setJsonPath(String jsonPath) {
        this.jsonPath = jsonPath;
    }

    public String getTestURL() {
        return testURL;
    }

    public void setTestURL(String testURL) {
        this.testURL = testURL;
    }

    public boolean isCheckLocatorUniqueness() {
        return checkLocatorUniqueness;
    }

    public void setCheckLocatorUniqueness(boolean checkLocatorUniqueness) {
        this.checkLocatorUniqueness = checkLocatorUniqueness;
    }

    public boolean isForceGenerateFiles() {
        return forceGenerateFiles;
    }

    public void setForceGenerateFiles(boolean forceGenerateFiles) {
        this.forceGenerateFiles = forceGenerateFiles;
    }

    public String getTestClassFullName() {
        return testClassFullName;
    }

    public void setTestClassFullName(String testClassFullName) {
        this.testClassFullName = testClassFullName;
    }

    public String getTestClassFilePath() {
        return testClassFilePath;
    }

    public void setTestClassFilePath(String testClassFilePath) {
        this.testClassFilePath = testClassFilePath;
    }

    public Class getManualClass() {
        return manualClass;
    }

    public void setManualClass(Class manualClass) {
        this.manualClass = manualClass;
    }

    public Class getTestClass() {
        return testClass;
    }

    public void setTestClass(Class testClass) {
        this.testClass = testClass;
    }
}
